config/routes.rb
Rails.application.routes.draw do

  get 'formation/retour' => 'formation#destroy', :as => "enleve"

  get 'mes_cours/litterature'

  get 'mes_cours/methode'

  get 'mes_cours/grammaire'

  get 'mes_cours/stylistique'

  resources :userlitts

  get 'log_out' => 'sessions#destroy', :as => "log_out"

  get 'log_in' => 'sessions#new', :as => "log_in"

  get 'sign_up' => 'users#new', :as => 'sign_up'

  get 'formation/module'

  get 'bibliotheque/parniveau'

  get 'bibliotheque/parsiecle'

  get 'bibliotheque/parauteur'

  get 'bibliotheque/methode'

  get 'bibliotheque/grammaire'

  get 'bibliotheque/stylistique'

  get 'bibliotheque/nouveautes'

  get 'accueil/connexion'

  get 'accueil/inscription'

  get 'accueil/visite'
  
  get 'accueil/bio'

  resources :mouvements
  resources :genres
  resources :lienthemes
  resources :themes
  resources :passages
  resources :auteurs
  resources :oeuvres
  resources :users
  resources :sessions

  get 'accueil/index'
  root :to => 'accueil#index'

end

app/models/auteur.rb
class Auteur < ActiveRecord::Base
	has_many :oeuvres
end

app/models/genre.rb
class Genre < ActiveRecord::Base
	has_many :oeuvres, foreign_key: "id"
end

app/models/lientheme.rb
class Lientheme < ActiveRecord::Base
	belongs_to :oeuvre, foreign_key: "oeuvre_id"
	belongs_to :theme, foreign_key: "theme_id"
end

app/models/mouvement.rb
class Mouvement < ActiveRecord::Base
	has_many :oeuvres, foreign_key: "mouvement_id"
end

app/models/oeuvre.rb
class Oeuvre < ActiveRecord::Base
	has_many :users, through: :userlitts
	belongs_to :auteur, foreign_key: "auteur_id"
	has_many :themes, through: :lienthemes
	belongs_to :genre, foreign_key: "genre_id"
	belongs_to :mouvement, foreign_key: "mouvement_id"
end

app/models/passage.rb
class Passage < ActiveRecord::Base
	belongs_to :oeuvre, foreign_key: "oeuvre_id"
end

app/models/theme.rb
class Theme < ActiveRecord::Base
	has_many :oeuvres, through: :lienthemes
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :oeuvres, through: :userlitts

	attr_accessor :password, :password_confirmation

	attr_accessor :password
	before_save :encrypt_password

	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email

	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
end

app/models/userlitt.rb
class Userlitt < ActiveRecord::Base
	belongs_to :oeuvre, foreign_key: "oeuvre_id"
	belongs_to :user, foreign_key: "user_id"

	validates_presence_of :oeuvre_id, :on => :create
	validates_presence_of :user_id, :on => :create
	validates_uniqueness_of :oeuvre_id, scope: [:user_id]

end

app/controllers/oeuvres_controller.rb
class OeuvresController < ApplicationController
  before_action :set_oeuvre, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate
  # GET /oeuvres
  # GET /oeuvres.json
  def index
    @oeuvres = Oeuvre.includes(:auteur, :genre, :mouvement).all
  end

  # GET /oeuvres/1
  # GET /oeuvres/1.json
  def show
    @lienthemes = Lientheme.where(oeuvre:@oeuvre)
    @passage = Passage.where(oeuvre:@oeuvre)
  end

  # GET /oeuvres/new
  def new
    @oeuvre = Oeuvre.includes(:auteur, :genre, :mouvement).new
    @auteur = Auteur.all
    @genre = Genre.all
    @mouvement = Mouvement.all
  end

  # GET /oeuvres/1/edit
  def edit
    @auteur = Auteur.all
    @genre = Genre.all
    @mouvement = Mouvement.all
  end

  # POST /oeuvres
  # POST /oeuvres.json
  def create
    @oeuvre = Oeuvre.new(oeuvre_params)

    respond_to do |format|
      if @oeuvre.save
        format.html { redirect_to oeuvres_url, notice: 'Oeuvre was successfully created.' }
        format.json { render :show, status: :created, location: @oeuvre }
      else
        format.html { render :new }
        format.json { render json: @oeuvre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oeuvres/1
  # PATCH/PUT /oeuvres/1.json
  def update
    respond_to do |format|
      if @oeuvre.update(oeuvre_params)
        format.html { redirect_to oeuvres_url, notice: 'Oeuvre was successfully updated.' }
        format.json { render :show, status: :ok, location: @oeuvre }
      else
        format.html { render :edit }
        format.json { render json: @oeuvre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oeuvres/1
  # DELETE /oeuvres/1.json
  def destroy
    @oeuvre.destroy
    respond_to do |format|
      format.html { redirect_to oeuvres_url, notice: 'Oeuvre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oeuvre
      @oeuvre = Oeuvre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def oeuvre_params
      params.require(:oeuvre).permit(:titre_oeuvre, :auteur_id, :genre, :mouvement, :genre_id, :mouvement_id, :date)
    end
end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/auteurs_helper.rb
module AuteursHelper
end

app/helpers/formation_helper.rb
module FormationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/lienthemes_helper.rb
module LienthemesHelper
end

app/helpers/mes_cours_helper.rb
module MesCoursHelper
end

app/helpers/mouvements_helper.rb
module MouvementsHelper
end

app/helpers/oeuvres_helper.rb
module OeuvresHelper
end

app/helpers/passages_helper.rb
module PassagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/userlitts_helper.rb
module UserlittsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/oeuvres/_form.html.erb
<%= form_for(@oeuvre) do |f| %>
  <% if @oeuvre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@oeuvre.errors.count, "error") %> prohibited this oeuvre from being saved:</h2>

      <ul>
      <% @oeuvre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titre_oeuvre %><br>
    <%= f.text_field :titre_oeuvre %>
  </div>

  <div class="field">
    <%= f.label :auteur_id %><br>
    <%= f.select("auteur_id", Auteur.all.collect {|p| [ p.nom_entier, p.id ] }, {selected: @oeuvre.auteur_id})%>
  </div>

  <div class="field">
    <%= f.label :genre_id %><br>
    <%= f.select("genre_id", Genre.all.collect {|p| [ p.titre_genre, p.id ] }, {selected: @oeuvre.genre.id})%>
  </div>

    <div class="field">
    <%= f.label :mouvement_id %><br>
    <%= f.select("mouvement_id", Mouvement.all.collect {|p| [ p.titre_mouvement, p.id ] }, {selected: @oeuvre.mouvement.id})%>
  </div>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.number_field :date %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/oeuvres/edit.html.erb
<%= form_for(@oeuvre) do |f| %>
  <% if @oeuvre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@oeuvre.errors.count, "error") %> prohibited this oeuvre from being saved:</h2>

      <ul>
      <% @oeuvre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titre_oeuvre %><br>
    <%= f.text_field :titre_oeuvre %>
  </div>

  <div class="field">
    <%= f.label :auteur_id %><br>
    <%= f.select("auteur_id", Auteur.all.order('nom_entier ASC').collect {|p| [ p.nom_entier, p.id ] }, {selected: @oeuvre.auteur_id})%>
  </div>

  <div class="field">
    <%= f.label :genre_id %><br>
    <%= f.select("genre_id", Genre.all.order('titre_genre ASC').collect {|g| [ g.titre_genre, g.id ] }, {selected: @oeuvre.genre_id})%>
  </div>

    <div class="field">
    <%= f.label :mouvement_id %><br>
    <%= f.select("mouvement_id", Mouvement.all.order('titre_mouvement ASC').collect {|m| [ m.titre_mouvement, m.id ] }, {selected: @oeuvre.mouvement_id})%>
  </div>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.number_field :date %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Voir', @oeuvre %> |
<%= link_to 'Retour aux oeuvres', oeuvres_path %> |

app/views/oeuvres/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Titre oeuvre</th>
      <th>Auteur</th>
      <th>Genre</th>
      <th>Mouvement</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @oeuvres.each do |oeuvre| %>
      <tr>
        <td><%= oeuvre.id %></td>
        <td><%= oeuvre.titre_oeuvre %></td>
        <td><%= oeuvre.auteur.nom_entier %></td>
        <td><%= oeuvre.genre.titre_genre %></td>
        <td><%= oeuvre.mouvement.titre_mouvement %></td>
        <td><%= oeuvre.date %></td>
        <td><%= link_to image_tag("voir.png"), oeuvre %></td>
        <td><%= link_to image_tag("edit.png"), edit_oeuvre_path(oeuvre) %></td>
        <td><%= link_to image_tag("suppr.png"), oeuvre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class= "ajouter"><%= link_to '+', new_oeuvre_path %></div>

app/views/oeuvres/new.html.erb
<%= form_for(@oeuvre) do |f| %>
  <% if @oeuvre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@oeuvre.errors.count, "error") %> prohibited this oeuvre from being saved:</h2>

      <ul>
      <% @oeuvre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titre_oeuvre %><br>
    <%= f.text_field :titre_oeuvre %>
  </div>

  <div class="field">
    <%= f.label :auteur_id %><br>
    <%= f.select("auteur_id", Auteur.all.order('nom_entier ASC').collect {|p| [ p.nom_entier, p.id ] }, {include_blank: '-'})%>
  </div>

  <div class="field">
    <%= f.label :genre_id %><br>
    <%= f.select("genre_id", Genre.all.order('titre_genre ASC').collect {|p| [ p.titre_genre, p.id ] }, {include_blank: '-'})%>
  </div>

    <div class="field">
    <%= f.label :mouvement_id %><br>
    <%= f.select("mouvement_id", Mouvement.all.order('titre_mouvement ASC').collect {|p| [ p.titre_mouvement, p.id ] }, {include_blank: '-'})%>
  </div>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.number_field :date %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Retour aux oeuvres', oeuvres_path %>

app/views/oeuvres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titre oeuvre:</strong>
  <%= @oeuvre.titre_oeuvre %>
</p>

<p>
  <strong>Auteur:</strong>
  <%= @oeuvre.auteur.nom_entier %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @oeuvre.genre.titre_genre %>
</p>

<p>
  <strong>Date de publication:</strong>
  <%= @oeuvre.date %>
</p>

<p>
  <strong>Passages:<br></strong>
    <% @passage.each do |p| %>
        <%= p.titre_passage %><br>
    <% end %>
<%= link_to 'Ajouter un passage', new_passage_path(@oeuvre) %>
</p>

<p>
  <strong>Thèmes:<br></strong>
    <% @lienthemes.each do |x| %>
        <%= x.theme.titre_theme %><br>
    <% end %>
<%= link_to 'Ajouter un thème', new_lientheme_path(@oeuvre) %>
</p>

<%= link_to 'Éditer', edit_oeuvre_path(@oeuvre) %> |
<%= link_to 'Retour aux oeuvres', oeuvres_path %> |