config/routes.rb
Rails.application.routes.draw do

  get 'formation/retour' => 'formation#destroy', :as => "enleve"

  get 'mes_cours/litterature'

  get 'mes_cours/methode'

  get 'mes_cours/grammaire'

  get 'mes_cours/stylistique'

  resources :userlitts

  get 'log_out' => 'sessions#destroy', :as => "log_out"

  get 'log_in' => 'sessions#new', :as => "log_in"

  get 'sign_up' => 'users#new', :as => 'sign_up'

  get 'formation/module'

  get 'bibliotheque/parniveau'

  get 'bibliotheque/parsiecle'

  get 'bibliotheque/parauteur'

  get 'bibliotheque/methode'

  get 'bibliotheque/grammaire'

  get 'bibliotheque/stylistique'

  get 'bibliotheque/nouveautes'

  get 'accueil/connexion'

  get 'accueil/inscription'

  get 'accueil/visite'
  
  get 'accueil/bio'

  resources :mouvements
  resources :genres
  resources :lienthemes
  resources :themes
  resources :passages
  resources :auteurs
  resources :oeuvres
  resources :users
  resources :sessions

  get 'accueil/index'
  root :to => 'accueil#index'

end

app/models/auteur.rb
class Auteur < ActiveRecord::Base
	has_many :oeuvres
end

app/models/genre.rb
class Genre < ActiveRecord::Base
	has_many :oeuvres, foreign_key: "id"
end

app/models/lientheme.rb
class Lientheme < ActiveRecord::Base
	belongs_to :oeuvre, foreign_key: "oeuvre_id"
	belongs_to :theme, foreign_key: "theme_id"
end

app/models/mouvement.rb
class Mouvement < ActiveRecord::Base
	has_many :oeuvres, foreign_key: "mouvement_id"
end

app/models/oeuvre.rb
class Oeuvre < ActiveRecord::Base
	has_many :users, through: :userlitts
	belongs_to :auteur, foreign_key: "auteur_id"
	has_many :themes, through: :lienthemes
	belongs_to :genre, foreign_key: "genre_id"
	belongs_to :mouvement, foreign_key: "mouvement_id"
end

app/models/passage.rb
class Passage < ActiveRecord::Base
	belongs_to :oeuvre, foreign_key: "oeuvre_id"
end

app/models/theme.rb
class Theme < ActiveRecord::Base
	has_many :oeuvres, through: :lienthemes
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :oeuvres, through: :userlitts

	attr_accessor :password, :password_confirmation

	attr_accessor :password
	before_save :encrypt_password

	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email

	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
end

app/models/userlitt.rb
class Userlitt < ActiveRecord::Base
	belongs_to :oeuvre, foreign_key: "oeuvre_id"
	belongs_to :user, foreign_key: "user_id"

	validates_presence_of :oeuvre_id, :on => :create
	validates_presence_of :user_id, :on => :create
	validates_uniqueness_of :oeuvre_id, scope: [:user_id]

end

app/controllers/passages_controller.rb
class PassagesController < ApplicationController
  before_action :set_passage, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate
  # GET /passages
  # GET /passages.json
  def index
    @passages = Passage.all
  end

  # GET /passages/1
  # GET /passages/1.json
  def show
  end

  # GET /passages/new
  def new
    @passage = Passage.new
  end

  # GET /passages/1/edit
  def edit
  end

  # POST /passages
  # POST /passages.json
  def create
    @passage = Passage.new(passage_params)

    respond_to do |format|
      if @passage.save
        format.html { redirect_to passages_url, notice: 'Passage was successfully created.' }
        format.json { render :show, status: :created, location: @passage }
      else
        format.html { render :new }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passages/1
  # PATCH/PUT /passages/1.json
  def update
    respond_to do |format|
      if @passage.update(passage_params)
        format.html { redirect_to passages_url, notice: 'Passage was successfully updated.' }
        format.json { render :show, status: :ok, location: @passage }
      else
        format.html { render :edit }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passages/1
  # DELETE /passages/1.json
  def destroy
    @passage.destroy
    respond_to do |format|
      format.html { redirect_to passages_url, notice: 'Passage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passage
      @passage = Passage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def passage_params
      params.require(:passage).permit(:oeuvre_id, :titre_passage, :video)
    end
end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/auteurs_helper.rb
module AuteursHelper
end

app/helpers/formation_helper.rb
module FormationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/lienthemes_helper.rb
module LienthemesHelper
end

app/helpers/mes_cours_helper.rb
module MesCoursHelper
end

app/helpers/mouvements_helper.rb
module MouvementsHelper
end

app/helpers/oeuvres_helper.rb
module OeuvresHelper
end

app/helpers/passages_helper.rb
module PassagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/userlitts_helper.rb
module UserlittsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/passages/_form.html.erb
<%= form_for(@passage) do |f| %>
  <% if @passage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@passage.errors.count, "error") %> prohibited this passage from being saved:</h2>

      <ul>
      <% @passage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :oeuvre_id %><br>
    <%= f.select("oeuvre_id", Oeuvre.all.order('titre_oeuvre ASC').collect {|p| [ p.titre_oeuvre, p.id ] }, {selected: @passage.oeuvre_id})%>
  </div>

  <div class="field">
    <%= f.label :titre_passage %><br>
    <%= f.text_field :titre_passage %>
  </div>

  <div class="field">
    <%= f.label :video %><br>
    <%= f.text_field :video %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/passages/edit.html.erb
<%= render 'form' %>

<%= link_to 'Voir', @passage %> |
<%= link_to 'Retour aux passages', passages_path %>

app/views/passages/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Oeuvre</th>
      <th>Titre passage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @passages.each do |passage| %>
      <tr>
        <td><%= passage.id %></td>
        <td><%= passage.oeuvre.titre_oeuvre %></td>
        <td><%= passage.titre_passage %></td>
        <td><%= link_to image_tag("play.jpg"), passage.video %></td>
        <td><%= link_to image_tag("voir.png"), passage %></td>
        <td><%= link_to image_tag("edit.png"), edit_passage_path(passage) %></td>
        <td><%= link_to image_tag("suppr.png"), passage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class= "ajouter"><%= link_to '+', new_passage_path %></div>

app/views/passages/new.html.erb
<%= render 'form' %>

<%= link_to 'Retour aux passages', passages_path %>

app/views/passages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Oeuvre:</strong>
  <%= @passage.oeuvre.titre_oeuvre %>
</p>

<p>
  <strong>Titre passage:</strong>
  <%= @passage.titre_passage %>
</p>

<p>
  <strong>Commentaire composé:</strong>
  <%= link_to "voir", @passage.video %>
</p>

<%= link_to 'Éditer', edit_passage_path(@passage) %> |
<%= link_to 'Retour aux passages', passages_path %> |