config/routes.rb
Rails.application.routes.draw do

  get 'formation/retour' => 'formation#destroy', :as => "enleve"

  get 'mes_cours/litterature'

  get 'mes_cours/methode'

  get 'mes_cours/grammaire'

  get 'mes_cours/stylistique'

  resources :userlitts

  get 'log_out' => 'sessions#destroy', :as => "log_out"

  get 'log_in' => 'sessions#new', :as => "log_in"

  get 'sign_up' => 'users#new', :as => 'sign_up'

  get 'formation/module'

  get 'bibliotheque/parniveau'

  get 'bibliotheque/parsiecle'

  get 'bibliotheque/parauteur'

  get 'bibliotheque/methode'

  get 'bibliotheque/grammaire'

  get 'bibliotheque/stylistique'

  get 'bibliotheque/nouveautes'

  get 'accueil/connexion'

  get 'accueil/inscription'

  get 'accueil/visite'
  
  get 'accueil/bio'

  resources :mouvements
  resources :genres
  resources :lienthemes
  resources :themes
  resources :passages
  resources :auteurs
  resources :oeuvres
  resources :users
  resources :sessions

  get 'accueil/index'
  root :to => 'accueil#index'

end

app/models/auteur.rb
class Auteur < ActiveRecord::Base
	has_many :oeuvres
end

app/models/genre.rb
class Genre < ActiveRecord::Base
	has_many :oeuvres, foreign_key: "id"
end

app/models/lientheme.rb
class Lientheme < ActiveRecord::Base
	belongs_to :oeuvre, foreign_key: "oeuvre_id"
	belongs_to :theme, foreign_key: "theme_id"
end

app/models/mouvement.rb
class Mouvement < ActiveRecord::Base
	has_many :oeuvres, foreign_key: "mouvement_id"
end

app/models/oeuvre.rb
class Oeuvre < ActiveRecord::Base
	has_many :users, through: :userlitts
	belongs_to :auteur, foreign_key: "auteur_id"
	has_many :themes, through: :lienthemes
	belongs_to :genre, foreign_key: "genre_id"
	belongs_to :mouvement, foreign_key: "mouvement_id"
end

app/models/passage.rb
class Passage < ActiveRecord::Base
	belongs_to :oeuvre, foreign_key: "oeuvre_id"
end

app/models/theme.rb
class Theme < ActiveRecord::Base
	has_many :oeuvres, through: :lienthemes
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :oeuvres, through: :userlitts

	attr_accessor :password, :password_confirmation

	attr_accessor :password
	before_save :encrypt_password

	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email

	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
end

app/models/userlitt.rb
class Userlitt < ActiveRecord::Base
	belongs_to :oeuvre, foreign_key: "oeuvre_id"
	belongs_to :user, foreign_key: "user_id"

	validates_presence_of :oeuvre_id, :on => :create
	validates_presence_of :user_id, :on => :create
	validates_uniqueness_of :oeuvre_id, scope: [:user_id]

end

app/controllers/lienthemes_controller.rb
class LienthemesController < ApplicationController
  before_action :set_lientheme, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate
  # GET /lienthemes
  # GET /lienthemes.json
  def index
    @lienthemes = Lientheme.all
  end

  # GET /lienthemes/1
  # GET /lienthemes/1.json
  def show
  end

  # GET /lienthemes/new
  def new
    @lientheme = Lientheme.new
  end

  # GET /lienthemes/1/edit
  def edit
  end

  # POST /lienthemes
  # POST /lienthemes.json
  def create
    @lientheme = Lientheme.new(lientheme_params)

    respond_to do |format|
      if @lientheme.save
        format.html { redirect_to lienthemes_url, notice: 'Lientheme was successfully created.' }
        format.json { render :show, status: :created, location: @lientheme }
      else
        format.html { render :new }
        format.json { render json: @lientheme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lienthemes/1
  # PATCH/PUT /lienthemes/1.json
  def update
    respond_to do |format|
      if @lientheme.update(lientheme_params)
        format.html { redirect_to lienthemes_url, notice: 'Lientheme was successfully updated.' }
        format.json { render :show, status: :ok, location: @lientheme }
      else
        format.html { render :edit }
        format.json { render json: @lientheme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lienthemes/1
  # DELETE /lienthemes/1.json
  def destroy
    @lientheme.destroy
    respond_to do |format|
      format.html { redirect_to lienthemes_url, notice: 'Lientheme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lientheme
      @lientheme = Lientheme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lientheme_params
      params.require(:lientheme).permit(:oeuvre_id, :theme_id)
    end
end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/auteurs_helper.rb
module AuteursHelper
end

app/helpers/formation_helper.rb
module FormationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/lienthemes_helper.rb
module LienthemesHelper
end

app/helpers/mes_cours_helper.rb
module MesCoursHelper
end

app/helpers/mouvements_helper.rb
module MouvementsHelper
end

app/helpers/oeuvres_helper.rb
module OeuvresHelper
end

app/helpers/passages_helper.rb
module PassagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/userlitts_helper.rb
module UserlittsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lienthemes/_form.html.erb
<%= form_for(@lientheme) do |f| %>
  <% if @lientheme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lientheme.errors.count, "error") %> prohibited this lientheme from being saved:</h2>

      <ul>
      <% @lientheme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :oeuvre_id %><br>
    <%= f.select("oeuvre_id", Oeuvre.all.order('titre_oeuvre ASC').collect {|p| [ p.titre_oeuvre, p.id ] }, {selected: @lientheme.oeuvre_id})%>
  </div>
  <div class="field">
    <%= f.label :theme_id %><br>
    <%= f.select("theme_id", Theme.all.order('titre_theme ASC').collect {|p| [ p.titre_theme, p.id ] }, {selected: @lientheme.theme_id})%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lienthemes/edit.html.erb
<%= render 'form' %>

<%= link_to 'Voir', @lientheme %> |
<%= link_to 'Retour aux lienthemes', lienthemes_path %>

app/views/lienthemes/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Oeuvre</th>
      <th>Theme</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lienthemes.each do |lientheme| %>
      <tr>
        <td><%= lientheme.id %></td>
        <td><%= lientheme.oeuvre.titre_oeuvre %></td>
        <td><%= lientheme.theme.titre_theme %></td>
        <td><%= link_to image_tag("voir.png"), lientheme %></td>
        <td><%= link_to image_tag("edit.png"), edit_lientheme_path(lientheme) %></td>
        <td><%= link_to image_tag("suppr.png"), lientheme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class= "ajouter"><%= link_to '+', new_lientheme_path %></div>

app/views/lienthemes/new.html.erb
<%= render 'form' %>

<%= link_to 'Retour aux lienthèmes', lienthemes_path %>

app/views/lienthemes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Oeuvre:</strong>
  <%= @lientheme.oeuvre.titre_oeuvre %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @lientheme.theme.titre_theme %>
</p>

<%= link_to 'Éditer', edit_lientheme_path(@lientheme) %> |
<%= link_to 'Retour aux lienthèmes', lienthemes_path %> |