config/routes.rb
Rails.application.routes.draw do

  get 'formation/retour' => 'formation#destroy', :as => "enleve"

  get 'mes_cours/litterature'

  get 'mes_cours/methode'

  get 'mes_cours/grammaire'

  get 'mes_cours/stylistique'

  resources :userlitts

  get 'log_out' => 'sessions#destroy', :as => "log_out"

  get 'log_in' => 'sessions#new', :as => "log_in"

  get 'sign_up' => 'users#new', :as => 'sign_up'

  get 'formation/module'

  get 'bibliotheque/parniveau'

  get 'bibliotheque/parsiecle'

  get 'bibliotheque/parauteur'

  get 'bibliotheque/methode'

  get 'bibliotheque/grammaire'

  get 'bibliotheque/stylistique'

  get 'bibliotheque/nouveautes'

  get 'accueil/connexion'

  get 'accueil/inscription'

  get 'accueil/visite'
  
  get 'accueil/bio'

  resources :mouvements
  resources :genres
  resources :lienthemes
  resources :themes
  resources :passages
  resources :auteurs
  resources :oeuvres
  resources :users
  resources :sessions

  get 'accueil/index'
  root :to => 'accueil#index'

end

app/models/auteur.rb
class Auteur < ActiveRecord::Base
	has_many :oeuvres
end

app/models/genre.rb
class Genre < ActiveRecord::Base
	has_many :oeuvres, foreign_key: "id"
end

app/models/lientheme.rb
class Lientheme < ActiveRecord::Base
	belongs_to :oeuvre, foreign_key: "oeuvre_id"
	belongs_to :theme, foreign_key: "theme_id"
end

app/models/mouvement.rb
class Mouvement < ActiveRecord::Base
	has_many :oeuvres, foreign_key: "mouvement_id"
end

app/models/oeuvre.rb
class Oeuvre < ActiveRecord::Base
	has_many :users, through: :userlitts
	belongs_to :auteur, foreign_key: "auteur_id"
	has_many :themes, through: :lienthemes
	belongs_to :genre, foreign_key: "genre_id"
	belongs_to :mouvement, foreign_key: "mouvement_id"
end

app/models/passage.rb
class Passage < ActiveRecord::Base
	belongs_to :oeuvre, foreign_key: "oeuvre_id"
end

app/models/theme.rb
class Theme < ActiveRecord::Base
	has_many :oeuvres, through: :lienthemes
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :oeuvres, through: :userlitts

	attr_accessor :password, :password_confirmation

	attr_accessor :password
	before_save :encrypt_password

	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email

	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
end

app/models/userlitt.rb
class Userlitt < ActiveRecord::Base
	belongs_to :oeuvre, foreign_key: "oeuvre_id"
	belongs_to :user, foreign_key: "user_id"

	validates_presence_of :oeuvre_id, :on => :create
	validates_presence_of :user_id, :on => :create
	validates_uniqueness_of :oeuvre_id, scope: [:user_id]

end

app/controllers/accueil_controller.rb
class AccueilController < ApplicationController
  def index
    @cours = Passage.count
  end

  def visite
  end

  def bio
  end

  def connexion
  end

  def inscription
  end
end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/auteurs_helper.rb
module AuteursHelper
end

app/helpers/formation_helper.rb
module FormationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/lienthemes_helper.rb
module LienthemesHelper
end

app/helpers/mes_cours_helper.rb
module MesCoursHelper
end

app/helpers/oeuvres_helper.rb
module OeuvresHelper
end

app/helpers/passages_helper.rb
module PassagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/userlitts_helper.rb
module UserlittsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accueil/admin.html.erb
<h1>Accueil</h1>

<%= link_to "Auteurs", auteurs_path %><br />
<%= link_to "Oeuvres", oeuvres_path %><br />
<%= link_to "Passages", passages_path %><br />
<%= link_to "Genres", genres_path %><br />
<%= link_to "Thèmes", themes_path %><br />
<%= link_to "Lienthèmes", lienthemes_path %><br />

app/views/accueil/bio.html.erb
<br><h1>Qui suis-je ?</h1>

app/views/accueil/index.html.erb
<%= link_to('users/new') do %><%= image_tag 'promo1.jpg', :class => 'imagepromo' %><% end %>
<div class = "promo">Découvrez <%= @cours%> cours vidéo en ligne accessibles à volonté !</div><br>

<%= link_to('users/new') do %><%= image_tag 'promo2.jpg', :class => 'imagepromo' %><% end %>
<div class = "promo">Tout le programme de français collège et lycée ! </div><br>

<%= link_to('users/new') do %><%= image_tag 'promo4.jpg', :class => 'imagepromo' %><% end %>
<div class = "promo">Une qualité égale sur tous les contenus ! </div><br>

<%= link_to('users/new') do %><%= image_tag 'promo3.jpg', :class => 'imagepromo' %><% end %>
<div class = "promo">Abonnement à 9€50 par mois, le prix d'un DVD ! </div><br>

<%= link_to('accueil/visite') do %>
<div class = "bouton">
Visite guidée</div>
<% end %>

<%= link_to('accueil/bio') do %>
<div class = "bouton">
Qui suis-je ?</div>
<% end %>

<%= link_to('users/new') do %>
<div class = "bouton">
Je m'inscris !</div>
<% end %>

app/views/accueil/visite.html.erb
<br><h1>Visite guidée</h1>